---

env:
  vms:
    fedora:
      cpu: 2                   # number of cpus
      memory: 2048             # amount of RAM memory
      clone: true              # use the linked_clone Vagrant feature
      autostart: true
      box: inclusivedesign/fedora24

stages:                # Stages to perform when 'ci test' command is invoked
  - setup              # name of the first stage to execute
  - test               # name of the second stage to execute

setup_job:
  stage: setup         # name of the stage
  script:
    - sudo ansible-galaxy install -fr provisioning/requirements.yml
    - sudo ansible-playbook provisioning/playbook.yml --extra-vars "@provisioning/vars.yml" --extra-vars "nodejs_app_install_dir=/vagrant" --tags="install,configure"

test_job:
  stage: test          # name of the stage
  script:              # One line per command to execute
    - node tests/AcceptanceTests.js
